lamp-php-apache:
  image: 'nestoru/lamp-php-apache:0.1' 
  restart: always
  container_name: lamp-php-apache 
  ports:
    - 80:80
    - 443:443
  links:
    - lamp-mysql
  volumes:
    - "${PHP_APP_DIR}:/var/www/html"
    - "${PHP_INI_PATH}:/usr/local/etc/php/php.ini"
    - "${BROWSCAP_INI_PATH}:/etc/browscap.ini"

lamp-mysql:
  image: 'mysql:5.7'
  restart: always
  container_name: lamp-mysql
  ports:
    - 3306:3306
  environment:
    - MYSQL_ROOT_PASSWORD=changeit! 
  volumes:
    - /opt/data/mysql:/var/lib/mysql 
